### ISSUE TITLE
Notify remove extra group assignment

### ISSUE THREAD

**Issue by pvullioud** [OSTraining/Simplerenew#370]
If a user is assigned to multiple groups, they are removed during the "notify" process of Recurly.

Exemple:
a user is assigned to a betaUser group in addition of the plan
at the next validation of his payment by Recurly, it'll lost the betaUser group

**Comment by nicksavov** [comment]
Hi Pierre-André,

In Simple Renew's options, is the "Multiple Subscriptions" option enabled?

If it's not enabled, what you're seeing is generally the desired effect, since a user should only have one user group under the paradigm.

**Comment by pvullioud** [comment]
Thanks Nick. I didn't see the option.
Maybe we can improve it. in our case other groups are not plans. they are regular Joomla groups to manage other ACL in the app.
I suggest to control it the user is assigned to only one plan but leave other J! group untouched

**Comment by billtomczak** [comment]
@pvullioud -- we did find some issues in  UG handling that should be resolved by [v1.1.16](https://github.com/OSTraining/Simplerenew/releases/tag/v1.1.16). Could you please verify?

**Comment by pvullioud** [comment]
We have le last version 1.1.16 I'll do more tests with  "Multiple Subscriptions" option enabled and give you some feedback

**Comment by billtomczak** [comment]
Pierre-André, if I understand properly what you are saying:

it should work as you expect. If a user is assigned to a user group that is **not** assigned to a subscription plan, SR shouldn't remove them from it. If, in your example the betaUser is assigned to any subscription plan, they will be removed from that group unless they subscribe to one of those plans. If betaUser is designated as the expiration plan, then it will also be removed as long as they have a current subscription to any plan.

Unless you want users to be subscribed to more than a single subscription, you should not turn on the multiple subscription option.

**Comment by gibiwatch** [comment]
Ok, it seems we were wrong and that existing users groups are kept. 
I still have some issues with incorrect groups assignments but that is a different matter, maybe I need to re-check our levels configuration.

**Comment by billtomczak** [comment]
Thanks! Good to hear SR seems to be behaving as we meant it to! :)

There is some possibility the group assignments got messed up due to problems I found in the previous versions.

I'm closing this issue as resolved. If you do find you are still having issues, please don't hesitate to open a new one here.

Thank you for the feedback!
